config/routes.rb
Rails.application.routes.draw do
  get "signup", to: "users#new"
  get "static_pages/home", to: "static_pages#home"
  get "static_pages/help", to: "static_pages#help"
  get "static_pages/about", to: "static_pages#about"
  get "static_pages/contact", to: "static_pages#contact"
  get "/", to: redirect("static_pages/home") # redirects root to home page
  root "static_pages#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint(8)        not null, primary key
#  email      :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = "")
    return if title.blank?

    title = title.titleize
    content_for :title, title
    tag.h1 title
  end

  def full_title(app_name)
    tag.title(content_for?(:title) ? "#{content_for :title} | #{app_name}" : app_name)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    = link_to "Ruby on Rails Tutorial", "https://www.railstutorial.org/"
    by
    = link_to "Michael Hartl", "http://www.michealhartl.com/"
  %nav
    %ul
      %li= link_to "About", static_pages_about_path
      %li= link_to "Contact", static_pages_contact_path
      %li= link_to "News", "http://news.railstutortial.org"

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "Chirpr", root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home", root_path
        %li= link_to "Help", static_pages_help_path
        %li= link_to "Sign Up", signup_path
        %li= link_to "Sign In", "#"

app/views/layouts/_rails_default.html.haml
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{ :src => '//html5shiv.googlecode.com/svn/trunk/html5.js' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    = full_title "Chirpr"
    = render "layouts/rails_default"
    = render "layouts/shim"
  %body{class: page_class}
    = render "layouts/header"
    .container
      = yield
      = render "layouts/footer"

app/views/static_pages/about.html.haml
= page_title("About")
%p
  The
  %em= link_to "Ruby on Rails Tutorial", "https://www.railstutorial.org/"
  is a
  = link_to "book", "https://www.railstutorial.org/book"
  and
  = link_to "screencast series", "https://screencasts.railstutorial.org/"
  to teach web development with
  = link_to "Ruby on Rails", "http://rubyonrails.org/"
  This is the sample application for the tutorial.

app/views/static_pages/contact.html.haml
= page_title("Contact")
%p
  Contact the Ruby on Rails Tutorial about the sample app at the
  = link_to "contact page", "https://www.railstutorial.org/contact"
  \.

app/views/static_pages/help.html.haml
= page_title("Help")
%p
  Get help on the Ruby on Rails Tutorial at the
  = link_to "Rails Tutorial help page", "https://www.railstutorial.org/help"
  To get help on this sample app, see the
  %em= link_to "Ruby on Rails Tutorial", "https://www.railstutorial.org/book"
  book

app/views/static_pages/home.html.haml
.center.jumbotron
  %h1 Chirpr
  %h2
    This is the home page for the
    = link_to "Ruby on Rails Tutorial", "https://www.railstutorial.org/"
    sample application.
  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"

app/views/users/new.html.haml
= page_title("Sign Up")
%p Find me in app/views/users/new.html.haml